use PlaystoreDB;
#----- TASK 3 ----

#Level 0

ALTER TABLE apps
ADD CONSTRAINT fk_developer
FOREIGN KEY (DeveloperID)
REFERENCES Developers(DeveloperID);

ALTER TABLE APPS
ADD CONSTRAINT fk_publisher
FOREIGN KEY (PublisherID)
REFERENCES PUBLISHERS(PublisherID);

ALTER TABLE APPS
ADD CONSTRAINT fk_category
FOREIGN KEY(CategoryID)
REFERENCES CATEGORIES(CategoryID);

SELECT *
FROM APPS
WHERE Rating > 4.5;

SELECT *
FROM APPS
WHERE Price = 0;

SELECT *
FROM APPS
WHERE CategoryID = 305;

#Level 1

SELECT *
FROM APPS
WHERE Downloads > 500000000;

SELECT *
FROM APPS
WHERE Rating BETWEEN 4.3 AND 4.7;

SELECT *
FROM APPS
WHERE Price IN(0,299);

SELECT *
FROM APPS
WHERE AppName LIKE "G%";

SELECT *
FROM APPS
WHERE AppName LIKE "%Google%";

SELECT *
FROM APPS
WHERE Rating > 4.0 AND Downloads > 500000000;

SELECT *
FROM APPS
WHERE CategoryID = 301 OR CategoryID = 305;

#Level 2

SELECT *
FROM APPS
WHERE NOT AppName LIKE "G%";

SELECT *
FROM APPS
WHERE Rating < 4.5 OR Downloads > 1000000000;

SELECT *
FROM DEVELOPERS
WHERE DeveloperName LIKE "%a%";

SELECT *
FROM APPS
WHERE Price BETWEEN 0 AND 300;

SELECT *
FROM APPS
WHERE PublisherID IN(201,204);

INSERT INTO APPS
VALUES
(6300,"Jujutsu Kaisen",110,203,305,4.0,55000000,0);

SELECT *
FROM APPS
WHERE NOT CategoryID = 305;